name: my_dbt_project
version: 1.0.0

config-version: 2

profile: default

models:
  advanced_test_2022:
    materialized: view
    sql: |
      SELECT *
      FROM username.advanced_test_2022

#source-paths:
#  - models
