name: actuaryllc
version: 1.0.0
config-version: 2
profile: actuaryllc
sources:
  - name: raw_data
    database: username  
    tables:
      - name: advanced_2022
models:
  actuaryllc:
    schema: public
    explore:
      description: A description of the explore model
      sql: models/explore_2022.sql
