name: hackathons
version: 1.0.0
config-version: 2
profile: actuaryllc

vars:
  PGUSER: actuary
  year_to_run: "2023"  # default to 2022 if not set

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

models:
  hackathons:
    "2022":
      enabled: "{{ env_var('year_to_run') == '2022' }}"
    "2023":
      enabled: "{{ env_var('year_to_run') == '2023' }}"

seeds:
  hackathons:
    "2022":
      +enabled: "{{ env_var('year_to_run') == '2022' }}"
    "2023":
      +enabled: "{{ env_var('year_to_run') == '2023' }}"
