name: actuaryllc
version: 1.0.0
config-version: 2
profile: actuaryllc
sources:
  raw_data:
    +enabled: true
models:
  actuaryllc:
    schema: public
    explore:
      description: A description of the explore model
      +materialized: table
      sql: models/explore_2022.sql
