name: actuaryllc
version: 1.0.0

config-version: 2

profile: actuaryllc

sources:
  - name: raw_data
    path: sources/sources.yml

models:
  actuaryllc:
    +schema: hackathons
    explore:
      description: 'A description of the explore model'
      sql: models/explore_2022.sql
