name: actuaryllc
version: 1.0.0

config-version: 2

profile: actuaryllc

sources:
  actuaryllc
    +enabled: true
  events:
    raw_data:
      advanced_2022:
        +enabled: true

models:
  actuaryllc:
    schema: hackathons
    explore:
      description: 'A description of the explore model'
      sql: models/explore_2022.sql
