name: actuaryllc
version: 1.0.0
config-version: 2
profile: actuaryllc

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
sources:
  tables:
    - name: 2022_advanced_test
    - name: 2022_advanced_train
    - name: 2022_sampled_submission
models:
  actuaryllc:
    staging:
      +materialized: table
