config:
  debug: true
  send_anonymous_usage_stats: false
    #skip_profile_setup: true

default:
  target: actuaryllc
  outputs:
    actuaryllc:
      type: postgres
      host: 192.168.190.81
      user: username
      password: password
      port: 5432
      dbname: username
      schema: hackathons
      threads: 4
      sslmode: disable
