version: 2

sources:
  - name: username
    description: A description of my PostgreSQL database
    loader: postgres
    database: username
    schema: hackathons
    tables:
      - name: advanced_test_2022
        description: A description of my_table
