version: 2
sources:
  - name: raw_data
    database: username
    schema: public
    tables:
      - name: advanced_2022
        freshness: # make this a little more strict
          warn_after: {count: 6, period: hour}
