name: actuaryllc
version: 1.0.0
config-version: 2
profile: actuaryllc

vars:
  PGUSER: ${env_var('PGUSER')}

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
models:
  actuaryllc:
    staging:
      +materialized: table
seeds:
  database: LLC
  #schema: hackathons <--- this adds a suffix to the schema
