config:
  debug: true
  send_anonymous_usage_stats: false
    #skip_profile_setup: true

vars:
  pg_user: ${env_var('PGUSER')}

actuaryllc:
  target: database
  outputs:
    database:
      type: postgres
      host: analytics.lan
      user: "{{ var('pg_user') }}"
      password: ${PGPASSWORD}
      port: 5432
      dbname: LLC
      schema: hackathons
      sslmode: disable
