config:
  debug: true
  send_anonymous_usage_stats: false
    #skip_profile_setup: true

actuaryllc:
  target: database
  outputs:
    database:
      type: postgres
      host: analytics.lan
      user: ${env_var('PGUSER')}
      password: ${env_var('PGPASSWORD')}
      port: 5432
      dbname: LLC
      schema: hackathons
      sslmode: disable
