config:
  debug: true
  send_anonymous_usage_stats: false
    #skip_profile_setup: true

actuaryllc:
  target: database
  outputs:
    database:
      type: postgres
      host: 192.168.190.81
      user: ${PGUSER}
      password: ${PGPASSWORD}
      port: 5432
      dbname: LLC
      schema: hackathons
      sslmode: disable
