version: '3'

networks:
  database-network:
    driver: overlay
      
services:
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
  db:
    image: postgres:16.1
    #hostname: database
    networks:
     - database-network
    ports:
     - 5432:5432
    environment:
      #https://hub.docker.com/_/postgres#environment-variables
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGSSLMODE: disable      
      #PGDATA: /var/opt/postgresql/data #storage folder for postgres data     
    volumes:
     - ./docker-entrypoints-initdb.d:/docker-entrypoint-initdb.d
     #- /data/postgres:/var/lib/postgresql/data
    # - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
#      - "/var/opt/postgresql/data:/var/lib/postgresql/data"
      #https://hub.docker.com/_/postgres#environment-variables
     #- ./POSTGRES_USER_FILE:/run/secrets/POSTGRES_USER_FILE
     #- ./POSTGRES_DB_FILE:/run/secrets/POSTGRES_DB_FILE
     #- ./POSTGRES_PASSWORD_FILE:/run/secrets/POSTGRES_PASSWORD_FILE
