name: 'redeploy postgres'
on:
  workflow_dispatch:
  push:
    branches:
      - main     
    paths:
      - 'postgres/postgres.yaml'
      
jobs:
  redeploy-service:
    runs-on: [actuary]
    env:
      PGHOST: ${{ vars.POSTGRES_HOST }}
      PGUSER: ${{ vars.POSTGRES_USER }}
      PGPORT: ${{ vars.POSTGRES_PORT }}
      PGDATABASE: ${{ vars.POSTGRES_DATABASE }}
      PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'AlexanderTroyScott/hackathon-predictive-analytics'
          ref: 'main'
      - name: Remove and redeploy services
        run: |
          SERVICES=("analytics_db") 
          for SERVICE_NAME in "${SERVICES[@]}"; do
            if docker service ls | grep -q $SERVICE_NAME; then
              docker service rm $SERVICE_NAME;
              echo "Service $SERVICE_NAME removed."
            else echo "Service $SERVICE_NAME is not running."
            fi
          done
      - run: chmod -R 777 docker-entrypoints-initdb.d 
      - run: docker stack deploy -c postgres.yaml analytics
      - name: Check environment variables
        run: |
          echo "PGHOST: $PGHOST"
          echo "PGUSER: $PGUSER"
          echo "PGPORT: $PGPORT"
          echo "PGDATABASE: $PGDATABASE"
          # Uncomment below line only if it's safe to print the password
          echo "PGPASSWORD: $PGPASSWORD"
