version: 2

sources:
  - name: raw_data
    schema: hackathons
    database: LLC
    tables:
      - name: 2022_advanced_train
      - name: 2022_advanced_test
      - name: 2022_sample_submission
      - name: 2023_expert_training
      - name: 2023_expert_testing
      - name: 2023_expert_samplesubmission
